roast/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import *
from roast.views import *
from roast.models import *

from tags.functions import *

urlpatterns = patterns('',
    url(r'^$', BatchList.as_view(), name='roast'),
    lr_url(r'^batches/$', BatchList.as_view(), name='batch_all'),
    lr_url(r'^batches/(?P<pk>\d+)/$', BatchEdit.as_view(), name='batch_edit'),
    lr_url(r'^batches/(?P<pk>\d+)/del/$', BatchDelete.as_view(), name='batch_delete'),
    lr_url(r'^batches/add/$', BatchAdd.as_view(), name='batch_add'),
)

roastery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from roast.api import *
from inventory.api import *

v1_api = Api(api_name = 'v1')
v1_api.register(BatchResource())
v1_api.register(RoastpointResource())
v1_api.register(EventResource())

v1_api.register(VarietyResource())

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('roast.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounting/', include('accounting.urls')),
    url(r'^roast/', include('roast.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^sales/', include('sales.urls')),
    url(r'^api/', include(v1_api.urls)),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

sales/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import *
from utilities.views import direct
from sales.views import *
from sales.models import *

from tags.functions import *

orders = direct('sales/order_list_ajax.html')

urlpatterns = patterns('',
    url(r'^$', OrderOutstanding.as_view(), name='sales'),
    lr_url(r'^customers/$', CustomerList.as_view(), name='customer_all'),
    lr_url(r'^customers/(?P<pk>\d+)/$', CustomerEdit.as_view(), name='customer_edit'),
    lr_url(r'^customers/(?P<pk>\d+)/del/$', CustomerDelete.as_view(), name='customer_delete'),
    lr_url(r'^customers/add/$', CustomerAdd.as_view(), name='customer_add'),
    lr_url(r'^orders/$', orders, name='order_all'),
    lr_url(r'^orders/(?P<pk>\d+)/$', OrderEdit.as_view(), name='order_edit'),
    lr_url(r'^orders/(?P<pk>\d+)/del/$', OrderDelete.as_view(), name='order_delete'),
    lr_url(r'^orders/add/$', OrderAdd.as_view(), name='order_add'),
    lr_url(r'^ordertransactions/add/$', OrderTransactionAdd.as_view(), name='ordertransaction_add'),
    lr_url(r'^ordertransactions/(?P<pk>\d+)/$', OrderTransactionEdit.as_view(), name='ordertransaction_edit'),
    lr_url(r'^ordertransactions/(?P<pk>\d+)/del/$', OrderTransactionDelete.as_view(), name='ordertransaction_delete'),
)

roast/models.py
from django.db import models
from django.core.urlresolvers import reverse_lazy
from roastery.models import SelflinkMixin
from datetime import datetime as dt

BATCH_STATES = ((0, 'Unroasted'),
                (1, 'Roasted'),)

class Batch(models.Model, SelflinkMixin):
    bag = models.ForeignKey('inventory.CoffeeBag')
    initial_weight = models.FloatField()
    date = models.DateField(blank=True, null=True)
    ambient_temp = models.FloatField(blank=True, null=True)
    program = models.CharField(max_length = 30, blank=True)
    target_temp = models.FloatField(blank=True, null=True)
    final_weight = models.FloatField(blank=True, null=True)
    order = models.ForeignKey('sales.Order')
    state = models.IntegerField(choices = BATCH_STATES, default = 0)

    class Meta:
        verbose_name_plural = 'Batches'

    def __unicode__(self):
        if self.date is None:
            return u"\u2610 {0}g of {1}".format(self.initial_weight, self.bag.variety)
        else:
            return u"\u2611 {0}: {1}g of {2}".format(self.date, self.initial_weight, self.bag.variety)

class RoastPoint(models.Model):
    time = models.TimeField()
    temp = models.FloatField()
    batch = models.ForeignKey(Batch)

    def __unicode__(self):
        return u"{0}: {1}deg K".format(self.time, self.temp)

class Event(models.Model):
    description = models.CharField(max_length = 30)

    def __unicode__(self):
        return self.description

sales/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from decimal import Decimal
from datetime import datetime as dt

from accounting.models import Account, CreditAccount, DebitAccount, Transaction, ExpenseAccount
from roast.models import Batch
from roastery.models import SelflinkMixin
from inventory.models import InventoryAccount

class Customer(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField(blank=True)

    def save(self):
        super(Customer, self).save()
        if len(CustomerPayable.objects.filter(customer = self)) == 0:
            a = CustomerPayable()
            a.customer = self
            a.save()
        if len(CustomerReceivable.objects.filter(customer = self)) == 0:
            a = CustomerReceivable()
            a.customer = self
            a.save()

    def __unicode__(self):
        return self.name

class CustomerPayable(CreditAccount):
    customer = models.ForeignKey(Customer)

    def __unicode__(self):
        return "{} payable [{}]".format(self.customer, self.pk)

class CustomerReceivable(DebitAccount):
    customer = models.ForeignKey(Customer)

    def __unicode__(self):
        return "{} receivable [{}]".format(self.customer, self.pk)

ORDER_STATUS = (
        (0, 'Initial',            ),
        (1, 'In progress',        ),
        (2, 'Paid and delivered', ),
        )

class Order(models.Model, SelflinkMixin):
    variety = models.ForeignKey('inventory.Variety')
    quantity = models.IntegerField()
    customer = models.ForeignKey(Customer)
    date = models.DateField()
    status = models.IntegerField(choices = ORDER_STATUS)

    def delivered_quantity(self):
        return 0

    # def determine_done(self):
    #     self.done = self.delivered_quantity() >= self.quantity

    def __unicode__(self):
        return u'{} {}/{} pcs {} for {}'.format(u'\u2611' if self.status < 2 else u'\u2610', \
                                                self.delivered_quantity(), \
                                                self.quantity, \
                                                self.variety, \
                                                self.customer )

class OrderTransaction(Transaction):
    order = models.ForeignKey(Order)


@receiver(post_save, sender=Batch)
def batch_saved(sender, instance=None, **kwargs):
    inv = InventoryAccount.objects.first()
    xa = ExpenseAccount.objects.first()
    t = OrderTransaction.objects.filter(order=instance.order, credit=inv).first()
    if not t:
        t = OrderTransaction()
        t.order = instance.order
        t.debit = xa
        t.credit = inv
        t.timestamp = dt.now()
    t.amount = instance.bag.price * Decimal( instance.initial_weight / instance.bag.weight )
    t.save()

sales/views.py
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from django.core.urlresolvers import reverse, reverse_lazy 
from utilities.views import FormMixin

from sales.models import *

def navbar_items():
    return [
            ( 'Sales', [
                        ('Customers', reverse('customer_all')),
                        ('Orders', reverse('order_all')),
                        # ('Outstanding orders', reverse('order_outstanding')),
                        ] ),
                ]

class OrderList(ListView):
    model = Order

class OrderOutstanding(OrderList):
    def get_queryset(self, *args, **kwargs):
        return Order.objects.filter(done=False)


class OrderDelete(FormMixin, DeleteView):
    model = Order  
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('order_all')

class OrderAdd(FormMixin, CreateView):
    model = Order
    template_name = 'form.html'

    def get_success_url(self, *args, **kwargs):
        return reverse('customer_edit', kwargs={ 'pk': self.object.customer.pk } )

    def get_initial(self, *args, **kwargs):
        i = super(OrderAdd, self).get_initial(*args, **kwargs)
        if 'customer' in self.request.GET.keys():
            i['customer'] = self.request.GET['customer']
        return i

class OrderEdit(FormMixin, UpdateView):
    model = Order
    template_name = 'sales/order_form.html'
    success_url = reverse_lazy('order_all')

    def get_context_data(self, *args, **kwargs):
        c = super(OrderEdit, self).get_context_data(*args, **kwargs)
        c['ts'] = OrderTransaction.objects.filter(order = self.object)
        c['bs'] = Batch.objects.filter(order = self.object)
        return c


class CustomerList(ListView):
    model = Customer

class CustomerDelete(FormMixin, DeleteView):
    model = Customer  
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('customer_all')

class CustomerAdd(FormMixin, CreateView):
    model = Customer
    template_name = 'form.html'
    success_url = reverse_lazy('customer_all')

class CustomerEdit(FormMixin, UpdateView):
    model = Customer
    template_name = 'sales/customer_form.html'

    def get_context_data(self, *args, **kwargs):
        c = super(CustomerEdit, self).get_context_data(*args, **kwargs)
        c['orders'] = Order.objects.filter(customer=self.object)
        return c


class OrderTransactionAdd(FormMixin, CreateView):
    model = OrderTransaction
    template_name = 'form.html'
    
    def get_success_url(self):
        return reverse('order_edit', self.object.order.pk)

    def get_form(self, *args, **kwargs):
        f = super(OrderTransactionAdd, self).get_form(*args, **kwargs)
        f.fields['debit'].queryset = Account.objects.select_subclasses()
        f.fields['credit'].queryset = Account.objects.select_subclasses()
        return f

    def get_initial(self, *args, **kwargs):
        i = super(OrderTransactionAdd, self).get_initial(*args, **kwargs)
        if 'order' in self.request.GET.keys():
            i['order'] = self.request.GET['order']
        return i

class OrderTransactionEdit(FormMixin, UpdateView):
    model = OrderTransaction
    template_name = 'form.html'
    success_url = reverse_lazy('coffeebag_nonempty')

    def get_form(self, *args, **kwargs):
        f = super(OrderTransactionEdit, self).get_form(*args, **kwargs)
        f.fields['debit'].queryset = Account.objects.select_subclasses()
        f.fields['credit'].queryset = Account.objects.select_subclasses()
        return f

class OrderTransactionDelete(FormMixin, DeleteView):
    model = OrderTransaction
    template_name = 'confirm_delete.html'

    def get_success_url(self, *args, **kwargs):
        return reverse('order_edit', kwargs={'pk': self.get_object().order.pk})

sales/templates/sales/customer_form.html
{% extends 'form.html' %}
{% load bootstrap %}

{% block right %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Related orders:</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Customer</th>
                        <th>Variety</th>
                        <th>Quantity</th>
                        <th>Done</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ob in orders %}
                    <tr>
                        <td>  {{ ob.date|date:'Y-M-d' }}  </td>
                        <td>                                         {{ ob.customer }} </td>
                        <td>                                         {{ ob.variety }} </td>
                        <td>                                         {{ ob.quantity }} </td>
                        <td>                                         {% if ob.done %}Yes{% else %}No{% endif %}
                        <a class="btn btn-default btn-sm pull-right" href="{% url 'order_edit' ob.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td> <a class="btn btn-default" href="{% url 'order_add' %}?customer={{ object.pk }}" >Add an order</a> </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

sales/templates/sales/customer_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped">
    <theader>
      <tr>
          <th>Name   </th>
          <th>Email</th>
      </tr>
    </theader>
    <tbody>
    {% if object_list %}
        {% for ob in object_list %}
            <tr>
                <td>  {{ ob.name    }}  </td>
                <td>                                           {{ ob.email }} 
                <a class="btn btn-default btn-sm pull-right" href="{% url 'customer_edit' ob.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
            </tr>
        {% endfor %}
    {% else %}
            <tr>
                <td>
                    <p>No customers have been created yet</p>
                </td>
            </tr>
    {% endif %}
        <tr>
            <td colspan="2">
                <a class="btn btn-primary" role="button" href="{% url 'customer_add' %}">Add a customer</a>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

sales/templates/sales/order_form.html
{% extends 'form.html' %}
{% load bootstrap %}

{% block right %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Related transactions:</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Date</th>   
                        <th>Amount</th>   
                        <th>Credit</th>   
                        <th>Debit</th>   
                    </tr>
                </thead>
                <tbody>
                {% for t in ts %}
                    <tr>
                        <td>{{ t.timestamp|date:"Y-m-d" }}</td>
                        <td>{{ t.amount }}</td>
                        <td>{{ t.credit }}</td>
                        <td>{{ t.debit }}
                        <a class="btn btn-default btn-sm pull-right" href="{% url 'ordertransaction_edit' t.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td colspan="5"> <a class="btn btn-default" href="{% url 'ordertransaction_add' %}?order={{ object.pk }}" >Add a transaction</a> </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Related batches:</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Roasting date</th>   
                        <th>Weight</th>   
                        <th>State</th>   
                    </tr>
                </thead>
                <tbody>
                {% for b in bs %}
                    <tr>
                        <td>{{ b.date|date:"Y-m-d"|default:"Not roasted yet" }}</td>
                        <td>{{ b.initial_weight }}</td>
                        <td>{{ b.get_state_display }}
                        <a class="btn btn-default btn-sm pull-right" href="{% url 'batch_edit' b.pk %}" ><span class="glyphicon glyphicon-pencil"></span></a></td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td> <a class="btn btn-default" href="{% url 'batch_add' %}?order={{ object.pk }}" >Add a batch</a> </td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

sales/templates/sales/order_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped">
    <theader>
      <tr>
          <th>Date</th>
          <th>Customer</th>
          <th>Variety</th>
          <th>Quantity</th>
          <th>Status</th>
      </tr>
    </theader>
    <tbody>
    {% if object_list %}
        {% for ob in object_list %}
            <tr>
                <td>  {{ ob.date|date:'Y-M-d' }}  </td>
                <td>                                         {{ ob.customer }} </td>
                <td>                                         {{ ob.variety }} </td>
                <td>                                         {{ ob.quantity }} </td>
                <td>                                         {{ ob.get_status_display }}
                <a class="btn btn-default btn-sm pull-right" href="{% url 'order_edit' ob.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
            </tr>
        {% endfor %}
    {% else %}
            <tr>
                <td>
                    <p>No orders have been created yet</p>
                </td>
            </tr>
    {% endif %}
        <tr>
            <td>
                <a class="btn btn-primary" role="button" href="{% url 'order_add' %}">Add a order</a>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

sales/templates/sales/order_list_ajax.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<table class="table table-striped">
    <theader>
    <tr>
        <th>Date</th>
        <th>Customer</th>
        <th>Variety</th>
        <th>Quantity</th>
        <th>Status</th>
        <th>Edit</th>
    </tr>
    </theader>
    <tbody id="orders">
        <tr data-template>

            {% verbatim %}
            <td>  {{ date|date 'YYYY-MM-DD' }}  </td>
            <td>  {{ customer.name }} </td>
            <td>  {{ variety.country }} {{ variety.area }} </td>
            <td>  {{ quantity }} </td>
            <td>  {{ get_status_display }} </td>
            {% endverbatim %}

            <td><a class="btn btn-default btn-sm" href=""><span class="glyphicon glyphicon-pencil"></span></a></td>
        </tr>
    </tbody>
</table>

<a class="btn btn-primary" role="button" href="{% url 'order_add' %}">Add a order</a>
{% endblock %}

{% block scripts %}
<script src="{% static 'sales\js\order_list.js' %}"> </script>
{% endblock %}