roast/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import *
from roast.views import *
from roast.models import *

from tags.functions import *

urlpatterns = patterns('',
    url(r'^$', BatchList.as_view(), name='roast'),
    lr_url(r'^batches/$', BatchList.as_view(), name='batch_all'),
    lr_url(r'^batches/(?P<pk>\d+)/$', BatchEdit.as_view(), name='batch_edit'),
    lr_url(r'^batches/(?P<pk>\d+)/del/$', BatchDelete.as_view(), name='batch_delete'),
    lr_url(r'^batches/add/$', BatchAdd.as_view(), name='batch_add'),
)

roastery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from roast.api import *
from inventory.api import *

v1_api = Api(api_name = 'v1')
v1_api.register(BatchResource())
v1_api.register(RoastpointResource())
v1_api.register(EventResource())

v1_api.register(VarietyResource())

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('roast.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounting/', include('accounting.urls')),
    url(r'^roast/', include('roast.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^sales/', include('sales.urls')),
    url(r'^api/', include(v1_api.urls)),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

roast/models.py
from django.db import models
from django.core.urlresolvers import reverse_lazy
from roastery.models import SelflinkMixin
from datetime import datetime as dt

BATCH_STATES = ((0, 'Unroasted'),
                (1, 'Roasted'),)

class Batch(models.Model, SelflinkMixin):
    bag = models.ForeignKey('inventory.CoffeeBag')
    initial_weight = models.FloatField()
    date = models.DateField(blank=True, null=True)
    ambient_temp = models.FloatField(blank=True, null=True)
    program = models.CharField(max_length = 30, blank=True)
    target_temp = models.FloatField(blank=True, null=True)
    final_weight = models.FloatField(blank=True, null=True)
    order = models.ForeignKey('sales.Order')
    state = models.IntegerField(choices = BATCH_STATES, default = 0)

    class Meta:
        verbose_name_plural = 'Batches'

    def __unicode__(self):
        if self.date is None:
            return u"\u2610 {0}g of {1}".format(self.initial_weight, self.bag.variety)
        else:
            return u"\u2611 {0}: {1}g of {2}".format(self.date, self.initial_weight, self.bag.variety)

class RoastPoint(models.Model):
    time = models.TimeField()
    temp = models.FloatField()
    batch = models.ForeignKey(Batch)

    def __unicode__(self):
        return u"{0}: {1}deg K".format(self.time, self.temp)

class Event(models.Model):
    description = models.CharField(max_length = 30)

    def __unicode__(self):
        return self.description

roast/views.py
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from django.core.urlresolvers import reverse, reverse_lazy 
from utilities.views import FormMixin

from roast.models import *

def navbar_items():
    return [
            ( 'Roast', [
                        ('Batches', reverse('batch_all')),
                        ] ),
                ]

class BatchList(ListView):
    model = Batch

class BatchOutstanding(BatchList):
    def get_queryset(self, *args, **kwargs):
        return Batch.objects.filter(done=False)


class BatchDelete(FormMixin, DeleteView):
    model = Batch  
    template_name = 'confirm_delete.html'
 
    def get_success_url(self):
        return reverse('order_edit', kwargs={'pk': self.object.order.pk})

class BatchAdd(FormMixin, CreateView):
    model = Batch
    template_name = 'form.html'
    
    def get_success_url(self):
        return reverse('order_edit', kwargs={'pk': self.object.order.pk})

    def get_initial(self, *args, **kwargs):
        i = super(BatchAdd, self).get_initial(*args, **kwargs)
        if 'order' in self.request.GET.keys():
            i['order'] = self.request.GET['order']
        return i

class BatchEdit(FormMixin, UpdateView):
    model = Batch
    template_name = 'roast/batch_form.html'
    
    def get_success_url(self):
        return reverse('order_edit', kwargs={'pk': self.object.order.pk})

roast/templates/roast/batch_form.html
{% extends 'form.html' %}
{% load bootstrap %}
{% load static %}

{% block right %}
<script>
    var pk = {{ object.pk }};
</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Roast points:</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Time</th>   
                    <th>Temp</th>   
                </tr>
            </thead>
            <tbody id='roastpoints'>
                {% verbatim %}
                <tr data-template>
                    <td>{{ time }}</td>
                    <td>{{ temp }}</td>
                </tr>
                {% endverbatim %}
            </tbody>
        </table>
    </div>
</div>

<div class="col-md-7">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Roast timer</h3>
        </div>
        <div class="panel-body">
            <div class="jumbotron">

                <h1 id="timer-display">00:00:00</h1>
                <a id="btn-start" class="btn btn-primary">Start</a>

            </div>

            <form>
                <fieldset>
                    <input id="inp-temp" type="number" />

                    <div class="btn-group">
                        <button id="btn-add" type="button" class="btn btn-default">Add</button>
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul id="events" class="dropdown-menu" role="menu" >
                            {% verbatim %}
                            <li data-template><a href="#">{{ description }}</a></li>
                            {% endverbatim %}
                        </ul>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'roast/js/batch_form.js' %}"> </script>
{% endblock %}

roast/templates/roast/batch_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped">
    <theader>
    <legend>Batches</legend>
      <tr>
          <th>Bag</th>
          <th>Initial weight</th>
          <th>Date</th>
          <th>Ambient temp</th>
          <th>Program</th>
          <th>Target temp</th>
          <th>Target time</th>
          <th>Final weight</th>
          <th>State</th>
          <th>Edit</th>
      </tr>
    </theader>
    <tbody>
    {% if object_list %}
        {% for ob in object_list %}
            <tr>
                <td>{{ ob.bag.variety }}</td>
                <td>{{ ob.initial_weight }}</td>
                <td>{{ ob.date|date:'Y-M-d' }}</td>
                <td>{{ ob.ambient_temp }}</td>
                <td>{{ ob.program }}</td>
                <td>{{ ob.target_temp }}</td>
                <td>{{ ob.target_time|time:"h:m:s" }}</td>
                <td>{{ ob.final_weight }}</td>
                <td>{{ ob.get_state_display }} </td>
                <td>
                <a class="btn btn-default btn-sm" href="{% url 'batch_edit' ob.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                </td>
            </tr>
        {% endfor %}
    {% else %}
            <tr>
                <td colspan="10">
                    <p>No batches have been created yet</p>
                </td>
            </tr>
    {% endif %}
        <tr>
            <td colspan="10">
                <a class="btn btn-primary" role="button" href="{% url 'batch_add' %}">Add a batch</a>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

roast/templates/roast/coffeebag_detail.html
<!doctype html>
{% extends 'roast/base.html' %}

{% block main %}
{% endblock %}

roast/templates/roast/coffeebag_list.html
{% extends 'roast/base.html' %}

{% block main %}
    <ul>
    {% for ob in object_list %}
    <a href="{% url 'bag_detail' ob.pk %}"><li>{{ ob }}</li></a>
    {% endfor %}
</ul>
{% endblock %}

roast/templates/roast/customer_list.html
{% extends 'roast/base.html' %}

{% block main %}
    <ul>
    {% for ob in object_list %}
    <a href="{% url 'customer_update' ob.pk %}"><li>{{ ob }}</li></a>
    {% endfor %}
</ul>
{% endblock %}

roast/templates/roast/detail_form.html
{% extends 'roast/base.html' %}

{% block main %}
<div>
<form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save" />
      <input type="submit" value="Delete" form="delete_form" />
</form>
{% if object %}
<form action="del/" method="post" id="delete_form" >{% csrf_token %}
</form>
{% endif %}
</div>
{% endblock %}

roast/templates/roast/order_detail.html
<!doctype html>
{% extends 'roast/base.html' %}

{% block main %}
<p>
<h2>{{ object }}</h2>
<table>
    <tr>
        <td>Date:</td><td>{{ object.date }}</td>
    </tr><tr>
        <td>Customer:</td><td>{{ object.customer }}</td>
    </tr><tr>
        <td>Description:</td><td>{{ object.description }}</td>
    </tr>
</table>
</p>
<p>
Associated batches:
    <ul>
    {% for ob in object.batch_set.all %}
    <a href="{% url 'batch_update' ob.pk %}"><li>{{ ob }}</li></a>
    {% endfor %}
    <a href="{% url 'order_batch_add' object.pk %}"><li>Add a batch</li></a>
    </ul>
</p>
<p>
Payment: {{ object.payment }}
{% endblock %}

roast/templates/roast/order_list.html
{% extends 'roast/base.html' %}

{% block main %}
    <ul>
    {% for ob in object_list %}
    <a href="{% url 'order_detail' ob.pk %}"><li>{{ ob }}</li></a>
    {% endfor %}
</ul>
{% endblock %}

roast/templates/roast/vendor_list.html
<!doctype html>
<html>
  <head>
    <title>BLAH</title>
  </head>
  <body>
    <ul>
    {% for vendor in object_list %}
    <li>{{ vendor }}</li>
    {% endfor %}
</ul>
  </body>
</html>